version: "3.1"
services:

  leave:

    build: ./leave


    container_name: angular

    ports:

      - "4200:4200"


  postgres:

    image: postgres:latest


    container_name: some-postgres

    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_HOST: some-postgres


    
    ports:

      - "5432:5432"
  

    volumes:


      - postgres_data:/var/lib/postgresql/data


 
  go-docker-demo:
    build: ./go-docker-demo

    container_name: gor

 
    ports:

      - "8080:8080"

    depends_on:

      - postgres


volumes:
  postgres_data: